#spring:
#  mail:
#    password: NEED_TO_INPUT
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: b90bc1e5d3cb03f82e1a16e8b9f1a6a0
            # 카카오 rest api key
  mail:
    password:
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname